global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "auto-affiliate-app"
    static_configs:
      - targets: ["localhost:7860"]
    metrics_path: /metrics
    scheme: http
